#define FRAME_WIDTH 23
#define FRAME_LENGTH 32 

#define LR_ANGLE 0
#define FB_ANGLE 0

#define WHEEL_CIRCUMFERENCE 0
#define WHEEL_DIST_PER_PULSE 0

//stick ports
#define PORT_SWERVE 1
#define PORT_ROTATE 2
#define PORT_OPERATOR 3

//wheel ports
#define LEFT_FRONT_SPEED_VIC 0
#define LEFT_FRONT_ANGLE_VIC 0
#define LEFT_FRONT_ANGLE_ENC_A 0
#define LEFT_FRONT_ANGLE_ENC_B 0

#define RIGHT_FRONT_SPEED_VIC 0
#define RIGHT_FRONT_ANGLE_VIC 0
#define RIGHT_FRONT_ANGLE_ENC_A 0
#define RIGHT_FRONT_ANGLE_ENC_B 0

#define LEFT_BACK_SPEED_VIC 0
#define LEFT_BACK_ANGLE_VIC 0
#define LEFT_BACK_ANGLE_ENC_A 0
#define LEFT_BACK_ANGLE_ENC_B 0

#define RIGHT_BACK_SPEED_VIC 0
#define RIGHT_BACK_ANGLE_VIC 0
#define RIGHT_BACK_ANGLE_ENC_A 0
#define RIGHT_BACK_ANGLE_ENC_B 0

//speed wheelunits change angle


#define GYRO_PORT 0

//Wheel ports
